### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by painlessjeff** [mc-17/pspack-flask#1]
Whenever I try to run the app I get the following error:

Traceback (most recent call last):
  File "/opt/pspack-flask/app.py", line 48, in <module>
    app.add_url_rule(app.static_url_path + '/<path:filename>',
  File "/home/jeff/.local/lib/python3.10/site-packages/flask/scaffold.py", line 57, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/jeff/.local/lib/python3.10/site-packages/flask/app.py", line 1090, in add_url_rule
    raise AssertionError(
AssertionError: View function mapping is overwriting an existing endpoint function: static

Running Python 3.10 on Arch Linux x64 if it matters.

Thanks a lot!

**Comment by owendswang** [comment]
Me the same error. Whatever in windows or ubuntu with python3 and flask installed.

**Comment by mc-17** [comment]
Oh no! I'll take a look in an hour or two and come up with a fix

**Comment by mc-17** [comment]
As a temporary fix:

1. Remove add_url_rule in app.pay
2. Move everything in static/9.0.0 to static
3. Remove 9.0.0 from the <script src> paths on templates/index.tpl

And it should work - I'll do a proper fix in a bit that doesn't require any of that

**Comment by mc-17** [comment]
Should be fixed now in commit:

8246353f35b267302ca29052d8da4624b734332a

Will give it a test myself before closing, give it a go if you want and let me know how it goes

**Comment by painlessjeff** [comment]
Seems to be fixed!

Thanks a lot!

**Comment by andrea-ap** [comment]
I use windows, i send comand of terminal and : 
Traceback (most recent call last):
  File "C:\app\app.py", line 3, in <module>
    from flask import Flask, render_template, request
ModuleNotFoundError: No module named 'flask'
