### ISSUE TITLE
Goldhen 2.1 Payload 

### ISSUE THREAD

**Issue by saildot4k** [mc-17/pspack-flask#16]
Goldhen 2.1 has been released and should replace the older version:
https://github.com/GoldHEN/GoldHEN

**Comment by lordlad** [comment]
You can easily do it yourself just by replacing the .bin file in the /payload folder with the v2.1 one and renaming it to the same filename (or edit this line "send(request.remote_addr, 9020, "payload/goldhen_2.0b2_900.bin")" in app.py to match the v2.1 .bin filename)

Don't think this should considered an 'issue'.

**Comment by mc-17** [comment]
Updated: https://github.com/mc-17/pspack-flask/releases/tag/release%2F1.1.4
