### ISSUE TITLE
Can't run as docker container after update to 1.20

### ISSUE THREAD

**Issue by skleffmann** [mc-17/pspack-flask#23]
Hi,

after upgrading to release 1.20, I can't start the docker container anymore, giving me the following error:

`Traceback (most recent call last):

  File "/opt/app.py", line 9, in <module>

    import requests

ModuleNotFoundError: No module named 'requests'`

Everything worked fine before. Setup is a ubuntu 22.04 lcx on proxmox, running python3.10.4.

**Comment by mc-17** [comment]
Aha, good catch - update requirements.txt with a new line like:

`requests`

Then build again. Does that fix your issue? If so I'll push a new release

**Comment by skleffmann** [comment]
Perfect, that did the trick.
The docker is working now.
