### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by 44daniel** [mc-17/pspack-flask#26]
I get this error on the host, how do you solve it??

\app.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
Version on disk (2.2.2) equal to or newer to latest (2.2.2

**Comment by mc-17** [comment]
Hello, these are two separate things:

```
\app.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
from distutils.version import LooseVersion
```

Is just a warning that something we use in the script is going to be removed from Python. It's a problem for me, not you :)

```
Version on disk (2.2.2) equal to or newer to latest (2.2.2
```

This is just letting you know that you've got an up-to-date GoldHEN, nothing wrong here
