### ISSUE TITLE
Docker image pspack-flask not found

### ISSUE THREAD

**Issue by gzubsc** [mc-17/pspack-flask#29]
Hi,

Maybe it's from my side - as I'm learning to use docker/linux - but it seems that your image "pspack-flask" is no more available in docker library. I tried with terminal (docker build pspack-flask) and with docker desktop: No results found.

In anyway, thanks for your work.

**Comment by mc-17** [comment]
> Hi,
> 
> Maybe it's from my side - as I'm learning to use docker/linux - but it seems that your image "pspack-flask" is no more available in docker library. I tried with terminal (docker build pspack-flask) and with docker desktop: No results found.
> 
> In anyway, thanks for your work.

No worries - I think your issue is that you're not building the image first (this image isn't on the Docker library, so pulling it will fail).

Instead, run `docker build -t pspack-flask .` from the directory with `Dockerfile`
